import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { Header } from "@/components/Header";
import { Toaster } from "sonner";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Provider>
          <QueryProvider>
            <main>
              <Header />
              {children}
            </main>
            <Toaster />
          </QueryProvider>
        </Provider>

      </body>
    </html>
  );
}
